# Generated by Django 4.1.5 on 2023-02-01 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_articlehits_article_hits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleHits',
            new_name='ArticleHit',
        ),
    ]
